### ISSUE TITLE
Receiving error: "New-IntuneWinPackage : The type initializer for 'PerTypeValues`1' threw an exception."

### ISSUE THREAD

**Issue by juharuotsalainen** [svrooij/ContentPrep#3]
I'm receiving error trying to make a intunewin-package:

```
PS C:\Program Files\WindowsPowerShell\Scripts> New-IntuneWinPackage -SourcePath "C:\temp\" -DestinationPath "C:\temp\new" -SetupFile "test.exe" -verbose -Debug
VERBOSE: Begin creating package
VERBOSE: Creating destination folder C:\temp\new
VERBOSE: Trying to create package for C:\temp\test.exe

Confirm
The type initializer for 'PerTypeValues`1' threw an exception.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
New-IntuneWinPackage : The type initializer for 'PerTypeValues`1' threw an exception.
At line:1 char:1
+ New-IntuneWinPackage -SourcePath "C:\temp\" -DestinationPath "C:\temp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-IntuneWinPackage], TypeInitializationException
    + FullyQualifiedErrorId : 1,SvR.ContentPrep.Cmdlet.NewIntuneWinPackageCommand
```

**Comment by svrooij** [comment]
1. You should not package to a sub folder of the folder you want to package.
2. As with the original tool, the setup file needs the full path

I do agree that it could give a better error message, and that is should check that the destination is not in the source

**Comment by juharuotsalainen** [comment]
Using the same folder for source and destination (and also using full path for setup) did not solve the issue:

`PS C:\Program Files\WindowsPowerShell\Scripts> New-IntuneWinPackage -SourcePath "C:\temp\" -DestinationPath "C:\temp\" -SetupFile "C:\temp\test.exe" -verbose -Debug
VERBOSE: Begin creating package
VERBOSE: Trying to create package for C:\temp\test.exe

Confirm
The type initializer for 'PerTypeValues`1' threw an exception.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
New-IntuneWinPackage : The type initializer for 'PerTypeValues`1' threw an exception.
At line:1 char:1
+ New-IntuneWinPackage -SourcePath "C:\temp\" -DestinationPath "C:\temp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-IntuneWinPackage], TypeInitializationException
    + FullyQualifiedErrorId : 1,SvR.ContentPrep.Cmdlet.NewIntuneWinPackageCommand`

**Comment by juharuotsalainen** [comment]
Here's the inner exception:
```
PS C:\Program Files\WindowsPowerShell\Scripts> $Error[0].Exception.InnerException
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system
cannot find the file specified.
```

**Comment by svrooij** [comment]
Are you running Powershell core or regular Powershell?

And you **cannot package to the same folder**!

Source c:\temp\source\
Destination c:\temp\destination\

**Comment by juharuotsalainen** [comment]
Same error even with `New-IntuneWinPackage -SourcePath "C:\temp\source" -DestinationPath "C:\temp\destination" -SetupFile "C:\temp\source\test.exe" -verbose -Debug`

I'm running the regular PowerShell that came bundled with Windows.

**Comment by svrooij** [comment]
Someone warned me about the fact that supporting regular Powershell will make your life as a developer so much harder.

**Comment by juharuotsalainen** [comment]
With PowerShell 7 it works great, thanks for the suggestion.
